### ISSUE TITLE
A2DP Hardware Offload 問題

### ISSUE THREAD

**Issue by TatshSiow** [4ragaki/android_device_xiaomi_elish#1]
無法關閉開發者選項中的 A2DP Hardware Offload
每次開關該功能都需要重啟才能切換

問題來源：https://xdaforums.com/t/rom-unofficial-a13-pixel-experience-plus-for-xiaomi-pad-5-pro-wifi-elish.4635584/post-89301094

**Comment by 4ragaki** [comment]
后续会解决这个问题，当前版本需要这个功能可以使用下面这个方法：

下载：[init.qcom.rc.txt](https://github.com/4ragaki/android_device_xiaomi_elish/files/14110906/init.qcom.rc.txt)

启用adb，lineageos 勾选使用root运行shell，连接usb

adb root
adb remount
adb push <rootdir/etc/init.qcom.rc> /vendor/etc/init/hw/init.qcom.rc
    * <*>改为下载的文件路径
更改 Bt A2dp offload设置，重启

**Comment by TatshSiow** [comment]
問題已處理！謝謝！
