### ISSUE TITLE
Pen and keyboard not working.

### ISSUE THREAD

**Issue by h4rm00n** [4ragaki/android_device_xiaomi_elish#2]
I flashed this rom under the guide in https://xdaforums.com/t/rom-unofficial-a13-pixel-experience-plus-for-xiaomi-pad-5-pro-wifi-elish.4635584/, but later I found that both pen and keyboard not working. The pen could be connected via bluetooth manually, but it's almostly useless. My pen is 1st generation.

**Comment by 4ragaki** [comment]
Well, I can't offer any help since I don't have access to those accessories.
You can paste [stock miui,custom rom] [adb log, kernel log] on [pen/kbd] [connecting, disconnecting,input] here,but I can't guarantee.
